# Generated by Django 6.0.1 on 2026-01-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height_u', models.PositiveIntegerField(default=42, help_text='Height in Rack Units (U)')),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_u', models.PositiveIntegerField(help_text='Bottom-most U position')),
                ('height_u', models.PositiveIntegerField(default=1, help_text='Height in U')),
                ('device_type', models.CharField(choices=[('server', 'Server'), ('switch', 'Switch'), ('router', 'Router'), ('pdu', 'PDU'), ('other', 'Other')], default='server', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('offline', 'Offline'), ('decommissioned', 'Decommissioned')], default='active', max_length=50)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.rack')),
            ],
        ),
    ]
