# Generated by Django 6.0.1 on 2026-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mounting_configuration',
            field=models.JSONField(default=list, help_text='List of occupied columns: front, middle, back'),
        ),
    ]
