# Generated by Django 6.0.1 on 2026-01-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_device_mounting_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.rack'),
        ),
    ]
