# Generated by Django 6.0.1 on 2026-04-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_device_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of string tags'),
        ),
        migrations.AlterField(
            model_name='device',
            name='position_u',
            field=models.PositiveIntegerField(blank=True, help_text='Bottom-most U position', null=True),
        ),
    ]
