# Generated by Django 6.0.1 on 2026-05-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_device_asset_tag_device_label_device_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.location'),
            preserve_default=False,
        ),
    ]
