# Generated by Django 6.0.1 on 2026-06-17 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_device_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only letters and spaces are allowed.')])),
                ('color', models.CharField(default='#374151', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='tags',
        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='devices', to='inventory.tag'),
        ),
    ]
