# Generated by Django 6.0.1 on 2026-06-17 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_tag_remove_device_tags_device_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visible_label', models.CharField(blank=True, max_length=100, null=True)),
                ('interface_type', models.CharField(choices=[('rj45', 'RJ-45 (1G)'), ('rj45_10g', 'RJ-45 (10G)'), ('sfp', 'SFP (1G)'), ('sfp_plus', 'SFP+ (10G)'), ('sfp28', 'SFP28 (25G)'), ('qsfp_plus', 'QSFP+ (40G)'), ('qsfp28', 'QSFP28 (100G)'), ('qsfp_dd', 'QSFP-DD (400G)'), ('osfp', 'OSFP (800G)'), ('cx4', 'CX4'), ('fc', 'Fibre Channel'), ('infiniband', 'InfiniBand'), ('wireless', 'Wireless'), ('virtual', 'Virtual'), ('other', 'Other')], default='rj45', max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('connected_port', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.port')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='inventory.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
    ]
